//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSignosVitales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int Idusuario { get; set; }
        public string fullname_doc { get; set; }
        public string usuario1 { get; set; }
        public string cotrasena { get; set; }
    }
}
